"use client";
import Link from "next/link";
import {usePathname,useRouter} from "next/navigation";
import {BookOpen,Menu,Sun,Moon,Monitor,LogOut,ArrowUpRight,Languages} from "lucide-react";
import {useTheme} from "next-themes";
import {useQueryClient} from "@tanstack/react-query";
import {useUI} from "@/hooks/ui-store";
import {Button} from "@/components/ui/button";
import {Modal} from "@/components/ui/dialog";
import {cn} from "@/lib/utils";
import type {UserDTO} from "@/types/domain";
import {useI18n} from "@/providers/i18n-provider";
export const memberLinks=["loans","reservations","wishlist","reviews","fines","payments","subscriptions","profile"];
export const adminLinks=["books","genres","users","loans","reservations","reviews","fines","payments","subscriptions"];
export function ThemeSwitch(){const {setTheme}=useTheme();const{t}=useI18n();return <div className="flex items-center rounded-md border p-1" aria-label={t("Color theme")}>{([{value:"light",label:"Light theme",Icon:Sun},{value:"dark",label:"Dark theme",Icon:Moon},{value:"system",label:"System theme",Icon:Monitor}] as const).map(({value,label,Icon})=><button key={value} onClick={()=>setTheme(value)} aria-label={t(label)} className="p-2 hover:bg-muted rounded"><Icon size={15}/></button>)}</div>;}
export function LanguageSwitch(){const{locale,setLocale,t}=useI18n();return <div className="flex items-center rounded-md border p-1" aria-label={t("Language")}><Languages size={15} className="mx-2 text-muted-foreground" aria-hidden/><button type="button" onClick={()=>setLocale("en")} aria-label={t("English")} aria-pressed={locale==="en"} className={cn("rounded px-2 py-1 text-xs font-semibold",locale==="en"&&"bg-primary text-primary-foreground")}>EN</button><button type="button" onClick={()=>setLocale("vi")} aria-label={t("Vietnamese")} aria-pressed={locale==="vi"} className={cn("rounded px-2 py-1 text-xs font-semibold",locale==="vi"&&"bg-primary text-primary-foreground")}>VI</button></div>}
export function Brand(){return <Link href="/" className="inline-flex gap-2 items-center text-xl font-bold tracking-tight"><span className="bg-primary text-primary-foreground p-2 rounded-md"><BookOpen size={20}/></span>folio<span className="text-primary">.</span></Link>;}
export function Header(){const{t}=useI18n();return <header className="border-b bg-card"><div className="max-w-7xl mx-auto px-5 py-4 flex items-center justify-between gap-5 flex-wrap"><Brand/><nav aria-label={t("Main navigation")} className="flex items-center gap-5 text-sm"><Link href="/books">{t("Catalog")}</Link><Link href="/genres">{t("Genres")}</Link><Link href="/dashboard">{t("My library")}</Link><Button asChild><Link href="/login">{t("Sign in")} <ArrowUpRight size={14}/></Link></Button></nav><div className="flex gap-2"><LanguageSwitch/><span className="hidden sm:block"><ThemeSwitch/></span></div></div></header>;}
export function Footer(){const{t}=useI18n();return <footer className="border-t mt-16"><div className="max-w-7xl mx-auto p-6 py-9 flex gap-6 flex-wrap justify-between text-sm text-muted-foreground"><span>{t("Folio Library - A little curiosity goes a long way.")}</span><Link href="/books">{t("Find your next read")}</Link><div className="flex gap-2"><LanguageSwitch/><ThemeSwitch/></div></div></footer>;}
export function PortalNav({user,admin}:{user:UserDTO;admin:boolean}) {
 const path=usePathname(),router=useRouter(),client=useQueryClient();const {sidebar,setSidebar}=useUI();const{t}=useI18n();
 const base=admin?"/admin":"/dashboard";
 const links=[{href:base,label:"Overview"},...(admin?adminLinks:memberLinks).map(s=>({href:base+"/"+s,label:s[0].toUpperCase()+s.slice(1)}))];
 async function logout(){await fetch("/api/session",{method:"DELETE"});client.clear();router.push("/login");router.refresh();}
 const menu=<nav aria-label={t(admin?"Administration":"Member navigation")} className="space-y-1">{links.map(l=><Link key={l.href} href={l.href} onClick={()=>setSidebar(false)} className={cn("block rounded-md px-4 py-2.5 text-sm",path===l.href?"bg-primary/10 text-primary font-semibold":"text-muted-foreground hover:bg-muted")}>{t(l.label)}</Link>)}</nav>;
 return <><aside className="hidden lg:flex fixed left-0 inset-y-0 w-60 border-r bg-card p-5 flex-col gap-8 z-30"><Brand/><div><p className="eyebrow mb-4 px-4">{t(admin?"Administration":"Your library")}</p>{menu}</div><div className="mt-auto border-t pt-5 space-y-4"><Link href="/books" className="text-sm text-muted-foreground">{t("Browse catalog")}</Link>{user.role==="ROLE_ADMIN"&&<Link className="block text-sm text-primary" href={admin?"/dashboard":"/admin"}>{t(admin?"Member portal":"Administration")}</Link>}<div className="flex flex-wrap gap-2"><LanguageSwitch/><ThemeSwitch/></div><Button variant="ghost" onClick={logout}><LogOut size={16}/>{t("Sign out")}</Button></div></aside><header className="border-b bg-card px-5 lg:px-9 py-4 flex gap-4 justify-between items-center"><button onClick={()=>setSidebar(true)} aria-label={t("Open navigation")} className="lg:hidden p-2"><Menu/></button><span className="text-sm text-muted-foreground">{t(admin?"Library operations":"Member workspace")}</span><span className="text-sm font-medium truncate">{user.fullName}</span></header><Modal open={sidebar} onOpenChange={setSidebar} title={t(admin?"Administration":"My library")} description={t("Navigate your library workspace.")}>{menu}<div className="mt-5 flex flex-wrap gap-3"><Button asChild variant="outline"><Link href="/books">{t("Catalog")}</Link></Button><Button variant="outline" onClick={logout}>{t("Sign out")}</Button><LanguageSwitch/><ThemeSwitch/></div></Modal></>;
}
