"use client";
import Link from "next/link";
import {useState} from "react";
import {useResource} from "@/hooks/query";
import {booksApi} from "./api";
import {Cover} from "@/components/books/book-card";
import {Loading,ErrorState,Empty,Pagination} from "@/components/ui/states";
import {ActionDialog} from "@/components/ui/action-dialog";
import {ReviewForm} from "@/features/reviews/review-form";
import {post} from "@/lib/api";

import {useI18n} from "@/providers/i18n-provider";
export function BookDetail({id}:{id:number}){const{t,date}=useI18n();const book=useResource(["book",id],()=>booksApi.detail(id));const [page,setPage]=useState(0);const reviews=useResource(["reviews",id,page],()=>booksApi.reviews(id,page));
 if(book.isPending)return <Loading/>;if(book.error)return <ErrorState error={book.error} retry={()=>void book.refetch()}/>;if(!book.data)return <Empty/>;
 const b=book.data;return <><Link href="/books" className="text-sm text-muted-foreground">{t("Back to catalog")}</Link><div className="grid md:grid-cols-[280px_1fr] lg:grid-cols-[320px_1fr] gap-8 lg:gap-14 mt-7"><Cover book={b} large/><div><p className="eyebrow">{b.genreName}</p><h1 className="heading mt-3">{b.title}</h1><p className="text-lg text-muted-foreground mt-3">{t("by {author}",{author:b.author})}</p><div className="inline-block rounded border px-3 py-1 text-sm text-success mt-5">{b.availableCopies>0?t("{count} copies available",{count:b.availableCopies}):t("Currently unavailable")}</div><p className="text-muted-foreground leading-relaxed my-7 whitespace-pre-wrap">{b.description||t("No description has been provided for this book.")}</p><div className="flex flex-wrap gap-3"><ActionDialog label="Borrow book" description="Your membership and borrowing eligibility will be checked by the library." numberField={{label:"Checkout days",initial:14}} action={v=>post("/api/book-loans/checkout",{bookId:id,checkoutDays:v.number})}/><ActionDialog label="Join reservation queue" description="Reserve an unavailable book. The library will confirm your queue position." action={()=>post("/api/reservations",{bookId:id})}/><ActionDialog label="Save to wishlist" description="Keep this book in your personal reading list." action={()=>post("/api/wishlist/add/"+id)}/></div><dl className="grid grid-cols-2 sm:grid-cols-3 gap-5 mt-9 border-t pt-6">{[["ISBN",b.isbn],["Publisher",b.publisher],["Published",date(b.publicationDate)],["Language",b.language],["Pages",b.pages],["Genre",b.genreName]].map(([key,value])=><div key={key}><dt className="text-xs text-muted-foreground mb-1">{t(String(key))}</dt><dd className="text-sm">{value??"-"}</dd></div>)}</dl></div></div><section className="mt-14 grid lg:grid-cols-[1.5fr_1fr] gap-8"><div><h2 className="text-2xl font-semibold mb-5">{t("Reader reviews")}</h2>{reviews.isPending?<Loading/>:reviews.error?<ErrorState error={reviews.error} retry={()=>void reviews.refetch()}/>:reviews.data?.content.length?<><div className="space-y-4">{reviews.data.content.map(r=><article className="panel" key={r.id}><div className="flex justify-between"><strong>{r.userName}</strong><span className="text-warning" aria-label={t("{rating} out of 5 stars",{rating:r.rating})}>{"★".repeat(r.rating)}{"☆".repeat(5-r.rating)}</span></div><h3 className="font-medium mt-3">{r.title}</h3><p className="text-muted-foreground mt-2 whitespace-pre-wrap">{r.reviewText}</p><time className="text-xs text-muted-foreground block mt-4">{date(r.createdAt)}</time></article>)}</div><Pagination page={page} total={reviews.data.totalPages} onChange={setPage}/></>:<Empty title="Be the first to share your thoughts" text="Reviews from members who have returned this book will appear here."/>}</div><div className="panel h-fit"><h2 className="font-semibold text-xl mb-5">{t("Share your reading experience")}</h2><ReviewForm bookId={id}/></div></section></>;
}
