"use client";
import Link from "next/link";
import Image from "next/image";
import {BookOpen,Heart} from "lucide-react";
import type {BookDTO} from "@/types/domain";
import {useAction} from "@/hooks/query";
import {post} from "@/lib/api";
import {useI18n} from "@/providers/i18n-provider";
export function Cover({book,large=false}:{book:BookDTO;large?:boolean}){const url=book.coverImageUrl;const optimized=!!url&&/^https:\/\/(covers.openlibrary.org|images.unsplash.com|i80zf4n4z0\.ufs\.sh)\//.test(url);return <div className={"relative flex items-center justify-center bg-muted overflow-hidden "+(large?"aspect-[3/4] rounded-lg":"aspect-[4/5] rounded-t-md")}>{url&&/^https?:\/\//.test(url)?<Image src={url} alt={book.title} fill sizes={large?"(max-width:768px) 90vw, 320px":"(max-width:640px) 45vw, 220px"} unoptimized={!optimized} className="object-contain p-5"/>:<div className="text-center px-5 text-muted-foreground"><BookOpen size={large?64:40} strokeWidth={1} className="mx-auto mb-4"/><p className="font-serif text-lg line-clamp-3">{book.title}</p></div>}</div>;}
export function BookCard({book}:{book:BookDTO}){const{t}=useI18n();const save=useAction(()=>post("/api/wishlist/add/"+book.id),t("Added to your wishlist"));return <article className="bg-card border rounded-md overflow-hidden group"><Link href={"/books/"+book.id} aria-label={t("View {title}",{title:book.title})}><Cover book={book}/></Link><div className="p-4"><div className="flex justify-between gap-2"><span className="eyebrow tracking-wide truncate">{book.genreName??t("Library collection")}</span><button disabled={save.isPending} onClick={()=>save.mutate()} aria-label={t("Add {title} to wishlist",{title:book.title})} className="text-muted-foreground hover:text-primary p-1 disabled:opacity-40"><Heart size={16}/></button></div><Link href={"/books/"+book.id} className="block font-semibold mt-2 line-clamp-2 leading-snug hover:text-primary">{book.title}</Link><p className="text-sm text-muted-foreground mt-1 truncate">{book.author}</p><p className={"text-xs mt-4 "+(book.availableCopies>0?"text-success":"text-warning")}>{t(book.availableCopies>0?"Available to borrow":"Currently unavailable")}</p></div></article>;}
