"use client";
import { useState } from "react";
import { useResource, useAction } from "@/hooks/query";
import { portalApi } from "./api";
import { PageHeader } from "@/components/ui/page-header";
import { Loading, ErrorState, Empty } from "@/components/ui/states";
import { Badge, statusTone } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { label, safeCheckout } from "@/lib/utils";
import {useI18n} from "@/providers/i18n-provider";
export function FinesPage(){const{t,money}=useI18n();const[status,setStatus]=useState("");const q=useResource(["my-fines",status],()=>portalApi.fines({status:status||undefined}));const pay=useAction(async(id:number)=>{const result=await portalApi.payFine(id);window.location.assign(safeCheckout(result.checkoutUrl));return result;},"");return <><PageHeader eyebrow="Account balance" title="Fines" description="Review charges from the library. Payment is confirmed only after secure verification by the payment provider."/><div className="mb-5 max-w-xs"><label htmlFor="fine-status">{t("Status")}</label><select id="fine-status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">{t("All fines")}</option>{["PENDING","PARTIALLY_PAID","PAID","WAIVED"].map(s=><option key={s} value={s}>{t(label(s))}</option>)}</select></div>{q.isPending?<Loading/>:q.error?<ErrorState error={q.error} retry={()=>void q.refetch()}/>:q.data?.length?<div className="overflow-x-auto panel p-0"><table><thead><tr><th>{t("Book")}</th><th>{t("Type")}</th><th>{t("Status")}</th><th>{t("Amount")}</th><th><span className="sr-only">{t("Actions")}</span></th></tr></thead><tbody>{q.data.map(f=><tr key={f.id}><td><strong>{f.bookTitle}</strong><br/><span className="text-xs text-muted-foreground">{f.reason}</span></td><td>{t(label(f.type))}</td><td><Badge tone={statusTone(f.status)}>{t(label(f.status))}</Badge></td><td>{money(f.amountOutstanding??f.amount)}</td><td className="text-right"><Button disabled={!['PENDING','PARTIALLY_PAID'].includes(f.status)||pay.isPending} onClick={()=>pay.mutate(f.id)}>{t("Pay securely")}</Button></td></tr>)}</tbody></table></div>:<Empty title="No fines" text="You have no charges in this view."/>}{pay.error&&<p className="text-destructive mt-4" role="alert">{t(pay.error.message)}</p>}</>}
