"use client";
import {useState} from "react";
import {useForm,type UseFormRegisterReturn} from "react-hook-form";
import {zodResolver} from "@hookform/resolvers/zod";
import {z} from "zod";
import {useAction} from "@/hooks/query";
import {adminApi} from "./api";
import {Button} from "@/components/ui/button";
import {Modal} from "@/components/ui/dialog";
import {useI18n} from "@/providers/i18n-provider";
const checkoutSchema=z.object({userId:z.coerce.number().int().positive(),bookId:z.coerce.number().int().positive(),days:z.coerce.number().int().min(1).max(30)});type CheckoutInput=z.input<typeof checkoutSchema>;type CheckoutValues=z.output<typeof checkoutSchema>;
export function StaffCheckout(){const{t}=useI18n();const[open,setOpen]=useState(false);const{register,handleSubmit,formState:{errors}}=useForm<CheckoutInput,unknown,CheckoutValues>({resolver:zodResolver(checkoutSchema),defaultValues:{days:14}});const mutation=useAction((v:CheckoutValues)=>adminApi.checkout(v.userId,v.bookId,v.days),t("Loan created"));return <><Button onClick={()=>setOpen(true)}>{t("Checkout for member")}</Button><Modal open={open} onOpenChange={setOpen} title="Checkout for member" description="Complete the borrower profile first. Overdue loans, borrowing limits and book availability are checked before checkout."><form className="space-y-4" onSubmit={handleSubmit(v=>mutation.mutate(v,{onSuccess:()=>setOpen(false)}))}><NumberField label="Member ID" error={errors.userId?.message} registration={register("userId")}/><NumberField label="Book ID" error={errors.bookId?.message} registration={register("bookId")}/><NumberField label="Checkout days" error={errors.days?.message} registration={register("days")}/>{mutation.error&&<p role="alert" className="text-destructive">{t(mutation.error.message)}</p>}<div className="flex justify-end gap-3"><Button type="button" variant="ghost" onClick={()=>setOpen(false)}>{t("Cancel")}</Button><Button disabled={mutation.isPending}>{t("Create loan")}</Button></div></form></Modal></>}
const fineSchema=z.object({bookLoanId:z.coerce.number().int().positive(),type:z.enum(["OVERDUE","DAMAGE","LOSS","PROCESSING"]),amount:z.coerce.number().int().positive(),reason:z.string().min(1).max(500)});type FineInput=z.input<typeof fineSchema>;type FineValues=z.output<typeof fineSchema>;
export function StaffFine(){const{t}=useI18n();const[open,setOpen]=useState(false);const{register,handleSubmit,formState:{errors}}=useForm<FineInput,unknown,FineValues>({resolver:zodResolver(fineSchema),defaultValues:{type:"OVERDUE"}});const mutation=useAction((v:FineValues)=>adminApi.createFine(v.bookLoanId,v.type,v.amount,v.reason),t("Fine created"));return <><Button onClick={()=>setOpen(true)}>{t("Create fine")}</Button><Modal open={open} onOpenChange={setOpen} title="Create fine" description="Create a charge against an existing loan. Enter the amount in the configured smallest currency unit."><form className="space-y-4" onSubmit={handleSubmit(v=>mutation.mutate(v,{onSuccess:()=>setOpen(false)}))}><NumberField label="Book loan ID" error={errors.bookLoanId?.message} registration={register("bookLoanId")}/><label>{t("Fine type")}<select {...register("type")}><option value="OVERDUE">{t("Overdue")}</option><option value="DAMAGE">{t("Damage")}</option><option value="LOSS">{t("Loss")}</option><option value="PROCESSING">{t("Processing")}</option></select></label><NumberField label="Amount" error={errors.amount?.message} registration={register("amount")}/><label>{t("Reason")}<textarea {...register("reason")}/>{errors.reason&&<span className="text-destructive text-sm">{t(String(errors.reason.message))}</span>}</label>{mutation.error&&<p role="alert" className="text-destructive">{t(mutation.error.message)}</p>}<div className="flex justify-end gap-3"><Button type="button" variant="ghost" onClick={()=>setOpen(false)}>{t("Cancel")}</Button><Button disabled={mutation.isPending}>{t("Create fine")}</Button></div></form></Modal></>}
function NumberField({label,error,registration}:{label:string;error?:string;registration:UseFormRegisterReturn}){const{t}=useI18n();return <label>{t(label)}<input type="number" min="1" {...registration}/>{error&&<span className="text-destructive text-sm">{t(error)}</span>}</label>}
